services:
  floci:
    image: floci/floci:1.5.20
    container_name: floci
    restart: no
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      FLOCI_STORAGE_MODE: memory
    networks:
      - floci_network

networks:
  floci_network:
    driver: bridge
